apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-ftp
  labels:
    app: vuln-ftp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vuln-ftp
  template:
    metadata:
      labels:
        app: vuln-ftp
    spec:
      containers:
      - name: vuln-ftp
        image: ajhanna/vuln-ftp
        ports:
        - containerPort: 27
        - containerPort: 21
        resources:
          limits:
            cpu: "600m"
            memory: "256Mi"
          requests:
            cpu: 200m
            memory: "64Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: vuln-ftp-service
  labels:
    app: vuln-ftp
spec:
  ports:
  - name: ftp
    port: 2121
    protocol: TCP
    targetPort: 21
  selector:
    app: vuln-ftp

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vuln-ftp-ingress
  annotations:
    kubenetes.io/ingress.class: "traefick"
spec:
  entryPoints:
  routes:
    services:
    - name: vuln-ftp
      port: 2121

