apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-lb
  namespace: ctf
spec:
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: ajhanna/dvwa
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources: 
          limits:
            cpu: "1000m"
            memory: "600Mi" 
          requests:  
            cpu: "400m"
            memory: "200Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
  namespace: ctf
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: "cookies"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-name: "route"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-ttl: "172800"
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: dvwa
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP: 
      timeoutSeconds: 10000
---

apiVersion:  autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: dvwalb-autoscaler
  namespace: ctf
spec:
  minReplicas: 3
  maxReplicas: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dvwa-lb
  targetCPUUtilizationPercentage: 30
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     targetAverageUtilization: 70
  # - type: Resource
  #   resource:
  #     name: memory
  #     targetAverageValue: "400Mi"
  
  
  
  
