apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-lb
  namespace: ctf
spec:
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: ajhanna/dvwa
        ports:
        - name: http
          containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
  namespace: ctf
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: "cookies"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-name: "route"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-ttl: "172800"
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: dvwa
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10000
---

apiVersion:  autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata: 
  name: dvwalb-autoscaler
  namespace: ctf
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dvwa-lb
  maxReplicas: 30
  minReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 40
  - type: Resource
    resource:
      name: memory
      targetAverageValue: "400Mi"

