apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-ssh-lb
  namespace: ctf
spec:
  selector:
    matchLabels:
      app: vuln-ssh
  template:
    metadata:
      labels:
        app: vuln-ssh
    spec:
      containers:
      - name: vuln-ssh
        image: ajhanna/vuln-ssh
        imagePullPolicy: Always
        ports:
        - name: ssh
          containerPort: 22
        resources: 
          limits:
            cpu: "1000m"
            memory: "600Mi" 
          requests:  
            cpu: "200m"
            memory: "200Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: vuln-ssh-service
  namespace: ctf
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: vuln-ssh
  type: LoadBalancer

---

# apiVersion:  autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: vuln-sshlb-autoscaler
#   namespace: ctf
# spec:
#   maxReplicas: 30
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       targetAverageUtilization: 40
#   - type: Resource
#     resource:
#       name: memory
#       targetAverageValue: "400Mi"
#   minReplicas: 3
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: vuln-sshlb

apiVersion:  autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: vuln-sshlb-autoscaler
  namespace: ctf
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Deployment
    name: vuln-sshlb
  targetCPUUtilizationPercentage: 60