apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-ftp
  labels:
    app: vuln-ftp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vuln-ftp
  template:
    metadata:
      labels:
        app: vuln-ftp
    spec:
      containers:
      - name: vuln-ftp
        image: ajhanna/vuln-ftp
        ports:
        - containerPort: 27
        - containerPort: 21
        resources:
          limits:
            cpu: "600m"
            memory: "256Mi"
          requests:
            cpu: 200m
            memory: "64Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: vuln-ftp-service
  labels:
    app: vuln-ftp
spec:
  ports:
  - name: ftps
    port: 27
    protocol: TCP
    targetPort: 27
  - name: ftp
    port: 20
    protocol: TCP
    targetPort: 20
  - name: highport1
    port: 13450
    protocol: TCP
    targetPort: 13450
  selector:
    app: vuln-ftp
  type: LoadBalancer

---


