apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-ftp
  labels:
    app: vuln-ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-ftp
  template:
    metadata:
      labels:
        app: vuln-ftp
    spec:
      containers:
      - name: vuln-ftp
        image: ajhanna/vuln-ftp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 13450
        - containerPort: 13451
        - containerPort: 13452
        - containerPort: 13453
        - containerPort: 13454
        - containerPort: 13455
        - containerPort: 13456
        - containerPort: 13457
        - containerPort: 13458
        - containerPort: 13459
        - containerPort: 13460
        resources:
          limits:
            cpu: "600m"
            memory: "256Mi"
          requests:
            cpu: 200m
            memory: "64Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: vuln-ftp-service
  labels:
    app: vuln-ftp
spec:
  ports:
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftp
    port: 20
    protocol: TCP
    targetPort: 20
  - name: passiveport1
    port: 13450
    protocol: TCP
    targetPort: 13450
  - name: passiveport2
    port: 13451
    protocol: TCP
    targetPort: 13451
  - name: passiveport3
    port: 13452
    protocol: TCP
    targetPort: 13452
  - name: passiveport4
    port: 13453
    protocol: TCP
    targetPort: 13453
  - name: passiveport5
    port: 13454
    protocol: TCP
    targetPort: 13454
  - name: passiveport6
    port: 13455
    protocol: TCP
    targetPort: 13455
  - name: passiveport7
    port: 13456
    protocol: TCP
    targetPort: 13456
  - name: passiveport8
    port: 13457
    protocol: TCP
    targetPort: 13457
  - name: passiveport9
    port: 13458
    protocol: TCP
    targetPort: 13458
  - name: passiveport10
    port: 13459
    protocol: TCP
    targetPort: 13459
  - name: passiveport11
    port: 13460
    protocol: TCP
    targetPort: 13460
  selector:
    app: vuln-ftp
  type: LoadBalancer

---


